[anydesk]
source = "aur"
aur = "anydesk-bin"

[bubblejail]
source = "github"
github = "igo95862/bubblejail"
use_latest_release = true

[cachyos-settings]
source = "github"
github = "CachyOS/CachyOS-Settings"
use_latest_release = true
prefix = "v"

[discord-ptb]
source = "aur"
aur = "discord-ptb"

[easyeffects]
source = "github"
github = "wwmm/easyeffects"
use_max_tag = true
prefix = "v"
exclude_regex = "(?i).*(alpha|beta).*"

[emptty]
source = "github"
github = "tvrzna/emptty"
use_latest_release = true
prefix = "v"

[ente-auth]
source = "github"
github = "ente-io/ente"
use_max_tag = true
include_regex = "^auth-v.*"
exclude_regex = "(?i).*(alpha|beta).*"
prefix = "auth-v"

[gearlever]
source = "github"
github = "mijorus/gearlever"
use_latest_release = true

[libmysofa]
source = "github"
github = "hoene/libmysofa"
use_latest_release = true
prefix = "v"

[mcpelauncher]
source = "github"
github = "minecraft-linux/mcpelauncher-manifest"
use_max_tag = true
include_regex = ".*-qt6$"
from_pattern = "^v(.*)-qt6$"
to_pattern = "\\1"

[mcpelauncher-ui-qt]
source = "github"
github = "minecraft-linux/mcpelauncher-ui-manifest"
use_max_tag = true
include_regex = ".*-qt6$"
from_pattern = "^v(.*)-qt6$"
to_pattern = "\\1"

[veracrypt]
source = "github"
github = "veracrypt/VeraCrypt"
use_max_tag = true
prefix = "VeraCrypt_"
exclude_regex = "(?i).*(alpha|beta).*"

[viber]
source = "aur"
aur = "viber"
